package org.xzc.msg.action.code;

public enum Code {

	SUCCESS(0), UNKNOWN_ERROR(1), NO_MESSAGE(2), WRONG_PASSWORD(3), LOGINED(4), WRONG_NAME_FORMAT(5), WRONG_PASSWORD_FORMAT(
			6), NAME_EXISTS(7), NOT_LOGIN(8), EMPTY_MESSAGE_TO_ADD(10), UNSUPPORTED_TYPE(11), INVALID_MESSAGE(12), USER_MESSAGE_REPETITION(
			13), NO_USER_MESSAGE(14), EXCEPTION(15), NO_USER(16), NO_AUTHORITY(17), NO_GROUP(18), REPEATED_USER_GROUP(
			19), REPEATED_MESSAGE_IN_GROUP(20), WRONG_USER_FORMAT(21), REPEATED_USER_IN_GROUP(22), INVALID_OPERATION(23);

	public final int value;

	private Code(int value) {
		this.value = value;
	}

}
